export const LATEST_BASIS_BY_NAME = "LATEST_BASIS_BY_NAME";
export const CLEAR_ARBITRAGE_STATE = "CLEAR_ARBITRAGE_STATE";
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
